### PR TITLE
[WIP] Add Dockerfile

### PR DESCRIPTION
**Pull request by canyon289**

### CODE REVIEW

**Comment by canyon289** [comment]
Trying to get ruby working in an ubuntu container was harder than just
using a ruby container and putting python in for myself.

So rather than a preference it was just "the easiest thing". If you can do
better, dont let me get in the way :D

**Comment by ericmjl** [comment]
Hahahaha, OK I see.

Is the intent to make a static site? If so, have you considered using mkdocs + mkdocs-material? You'll get something like these:

- https://fastapi.tiangolo.com
- https://ericmjl.github.io/Network-Analysis-Made-Simple/
- https://ericmjl.github.io/bayesian-analysis-recipes/

Then again, you've probably got a set of habits that you're used to, so no pressure here. Just thought I'd bring it up.

**Comment by canyon289** [comment]
The choice of jupyter-books was made by Osvaldo, and I actually really like
jupyter-book, so I was sticking by that but just trying to get jekyll site
to build locally.

**Comment by ericmjl** [comment]
Gotcha!

**Comment by aloctavodia** [comment]
@canyon289 Do you want to update this, or should we close?

**Pull request closed without merging**
